import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navigation from "../components/Navigation";

import Providers from '../lib/Provider';

import AuthHydrator from "../components/AuthHydrated";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <AppRouterCacheProvider>
          <Providers>
            <Navigation />
            <main className="pt-20 pr-8 pl-8">
              <AuthHydrator />
              {children}
            </main>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
